proxy.host=127.0.0.1
proxy.port=1916

backend.baseUrl=http://127.0.0.1:1914

# rutas de API1 que quieres exponer en el proxy
backend.routes=/health,/login,/usuarios,/tickets,/events,/events-with-types,/ticket-types,/buy-tickets,/register-account,/hola,/payment-webhook,/purchases